apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.azure.tablestorage
  version: v1
  metadata:
  - name: accountName
    value: "wisdompetmed"
  - name: accountKey
    value: "4CHcIUksdecIJnVEHiJoiwbf/JBOVFM7AaiAO3MhjDCtn753ZvdVq5JCQPlRbt2V3mwxVQEKLfrycz2Z0krW1w=="
  - name: tableName
    value: "state"